# Generated by Django 4.0.1 on 2022-01-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shorthand', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField(unique=True)),
                ('markets_page', models.URLField(unique=True)),
                ('base_xpath', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NTD', 'Not Traded'), ('DCS', 'Diff Coin Shorthand'), ('DXP', 'Diff Xpath')], max_length=3)),
                ('value', models.CharField(max_length=1000)),
                ('forCoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
                ('forExchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.exchange')),
            ],
            options={
                'unique_together': {('forCoin', 'forExchange', 'kind')},
            },
        ),
    ]
