# Generated by Django 4.0.1 on 2022-01-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='wait_xpath',
            field=models.CharField(default='TODO', max_length=1000),
            preserve_default=False,
        ),
    ]
